### ISSUE TITLE
 Intermittent test failures with TSO commands/APIs

### ISSUE THREAD

**Issue by JTonda** [zowe/zowe-cli#69] opened 2018-10-09 21:07 UTC
_From @MarkAckert on April 17, 2018 12:26_

[MIGRATED]

On master (and other branches), I receive intermittent test failures for some of the TSO API (and command) tests.

Example:
```
 FAIL  packages\zostso\__tests__\__system__\api\api.TsoStop.test.ts (7.246s)
  ● StopCommand (integration) › stop should succeed with correct parameters

    expect(received).not.toBeDefined()

    Expected value not to be defined, instead received
      [Error: Expect Error: [object Object]No servlet key was supplied.]

      128 |             Imperative.console.info(`Error ${error.details.msg}`);
      129 |         }
    > 130 |         expect(error).not.toBeDefined();
      131 |         expect(response).toBeDefined();
      132 |         expect(response.success).toEqual(true);
      133 |         expect(response.servletKey).toEqual(activeServletKey);

      at Object.<anonymous> (packages/zostso/__tests__/__system__/api/api.TsoStop.test.ts:130:27)
          at Generator.throw (<anonymous>)
      at rejected (packages/zostso/__tests__/__system__/api/api.TsoStop.test.ts:29:63)
```

What is "odd" is that the failures seem to disappear after a few "npm run test" executions (and I don't experience the failures until a day or so later). 

[COMMENTS]

Cancelling outstanding TSO address spaces seems to "help". We need to ensure we're "cleaning up" after tests.

_Copied from original issue: gizafoundation/brightside#9_

**Comment by MarkAckert** [comment] 2022-09-29 20:02
Could not reproduce. Closing.

**Closed by MarkAckert** 2022-09-29 20:02 UTC
Labels: question, testing, priority-low
