### ISSUE TITLE
`zowe uss issue ssh` command returns no output when there is an invalid port in the SSH profile

### ISSUE THREAD

**Issue by plavjanik** [zowe/zowe-cli#542] opened 2019-10-09 07:29 UTC
If you have an invalid port in the SSH profile, in this case, the z/OSMF port, then the `zowe uss issue ssh "echo Hello"` does not return anything and the return code is `0`.

The profile has been created by: `zowe profiles create ssh-profile ca32 --host ca32.lvn.broadcom.net --port 1443 --user plape03 --password "***"`

It happens to a lot of users that are setting up both z/OSMF and SSH profiles and they just change the type of profile to ssh from zosmf and keep the z/OSMF port for the SSH profile.

The expected behavior would be to return some error that will help users to find out that there is something wrong with the ssh profile.

**Comment by tucker01** [comment] 2019-10-10 11:28
Makes sense. I'm guessing we're not surfacing something from the ssh connect.

**Comment by tjohnsonBCM** [comment] 2019-10-24 12:09
This issue seems related to #416.

**Comment by MarkAckert** [comment] 2022-09-30 15:31
Closing as a duplicate of #416 .

**Closed by MarkAckert** 2022-09-30 15:31 UTC
Labels: bug, priority-low
