### ISSUE TITLE
Zowe CLI online reference is not accessible from documentation

### ISSUE THREAD

**Issue by plavjanik** [zowe/zowe-cli#1029] opened 2021-06-15 08:48 UTC
The pages https://docs.zowe.org/stable/appendix/zowe-cli-commannd-reference.html points to "Zowe CLI command reference guide" via the Browse Online link

![image](https://user-images.githubusercontent.com/7644758/122022777-379aa600-cdc7-11eb-8afa-40ae53eb7f0f.png)

This results in an 404 error:
![image](https://user-images.githubusercontent.com/7644758/122022821-44b79500-cdc7-11eb-88ba-4047e5d65bad.png)

**Comment by t1m0thyj** [comment] 2021-06-15 12:26
I'm able to reproduce this error, but am confused why it happens only when clicking the link on that page, since the docs.zowe.org homepage has the same link which works:

![image](https://user-images.githubusercontent.com/22344007/122052014-38294180-cdb3-11eb-8cfe-6d9a9076071f.png)
![image](https://user-images.githubusercontent.com/22344007/122052123-57c06a00-cdb3-11eb-8959-ab6101993a3f.png)

**Comment by plavjanik** [comment] 2021-06-15 14:00
Thank you for showing me a way that works. Does it make sense to transfer the issue to `zowe/docs-site` so the problem in the documentation can be researched?

Both zowe.org home page and the Zowe documentation change the URL in the browser to the same: https://docs.zowe.org/stable/web_help/index.html

But the Zowe documentation prevents loading of the new locations (no request is made by the browser to https://docs.zowe.org/stable/web_help/index.html).

The DOM is:
```html
<a href="/stable/web_help/index.html" class="">Browse online</a>
```

I guess that the documentation website has some code to process links that are not fully qualified and there leads to 404 because `/stable/web_help/index.html` is not a documentation page but Zowe web help.

**Comment by plavjanik** [comment] 2021-06-15 14:02
Btw. web help is great. It helps me a lot and I recommend it to everyone. I usually use `zowe --web-help` but someone else wanted the online version and we ran into the reported problem.

**Comment by t1m0thyj** [comment] 2021-11-05 20:59
This seems to be fixed on the new Zowe docs site (that uses Docusaurus).

**Closed by t1m0thyj** 2021-11-05 20:59 UTC
