### ISSUE TITLE
renaming a config file with secure credentials

### ISSUE THREAD

**Issue by tucker01** [zowe/zowe-cli#967] opened 2021-03-03 17:32 UTC
When using the new config with secured fields, if I rename/move the config file, I lose my secured fields. Is there a way we can make the config file (and secured fields) resilient to rename/move? 

Some additional details on possible solutions here: #950

**Comment by t1m0thyj** [comment] 2021-03-12 14:09
@VitGottwald has pointed out the issue is easier to reproduce than renaming/moving a config file. Secure fields are also lost if you rename/move a profile within a config file (e.g., renaming profile "lpar1" to "lpar2").

**Comment by zFernand0** [comment] 2021-07-27 19:04
Many solutions for this one issue. I'll try to list them from best to worst 😋 

**Option 1**
Estimate: 13 points
Approach: Dissociate config file and profile property paths from secure values.
Method: Switch from `secure: string[]` to `secure: { [propertyId: string]: [propertyName: string] }`

**Option 2**
Estimate: 13 points
Approach: Dissociate config file and profile property paths from secure values.
Method: Replace secure property values with `{ "__secure__": [propertyId: string] }`
⚠️ Breaking Change. See [Option 1 on Timothy's gist](https://gist.github.com/t1m0thyj/c142c668a4353844d469901cf7ce3634#alternative-approaches-that-have-been-suggested)

**Option 3**
Estimate: 13 points
Approach: "Caching"
Method:
- Store duplicate of `secure_config_props` in the vault.
- Instead of throwing a `missing properties error`, do a `diff` between `secure_config_props` and duplicate. 
  - If a path for a secure property changed (config file path, or profile name), either:
    - Warn the user before attempting to use the old value (and store/update `secure_config_props` and duplicate)
    - Warn the user that a path changed, and prompt if old value should be used. 😢 Then store/update vault.

**Option X**
⛔ Not an option ⛔ 😋 
Estimate: 3 points
Approach: `wontfix`
Method: Document and communicate current workarounds, i.e. run `zowe config secure` and provide all values.

**Comment by MikeBauerCA** [comment] 2021-07-28 16:42
#923 is a higher priority and may sufficiently accommodate this situation

**Comment by gejohnston** [comment] 2022-10-18 15:40
The following issues were addressed before the release of Zowe V2:
[Consistent "login" experience for various configurations #923](https://github.com/zowe/zowe-cli/issues/923)
[ Secure credentials - JSON path #950 ](https://github.com/zowe/zowe-cli/issues/950)
Those issues were chosen to address this area of concern.

This enhancement has had no activity for 12 months. No action on this enhancement is targeted for the next 2 calendar quarters. Therefore, this enhancement is being closed.

**Closed by gejohnston** 2022-10-18 15:40 UTC
Labels: enhancement, team-profile, priority-medium
