### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open '/root/.zowe/imperative/logs/imperative.log'

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#181] opened 2019-01-22 15:59 UTC
I did an uninstall and reinstall of the CLI on RedHat.  This is probably similar to #180, but it seems like there is an unhandled promise to address.  Or, is this the proper message?
```
[root@<USER>-T20241 ~]# sudo npm install -g @brightside/core@2.0.0-next.201901181325
npm WARN deprecated circular-json@0.5.9: CircularJSON is in maintenance only, flatted is its successor.
/usr/bin/zowe -> /usr/lib/node_modules/@brightside/core/lib/main.js
/usr/bin/bright -> /usr/lib/node_modules/@brightside/core/lib/main.js

> @brightside/core@2.0.0-next.201901181325 postinstall /usr/lib/node_modules/@brightside/core
> node ./scripts/validatePlugins

Since you re-installed Zowe CLI, we are re-validating any plugins.
(node:26373) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, open '/root/.zowe/imperative/logs/imperative.log'
    at Object.openSync (fs.js:439:3)
    at Object.writeFileSync (fs.js:1190:35)
    at Object.appendFileSync (fs.js:1236:6)
    at writeTheChunk (/usr/lib/node_modules/@brightside/core/node_modules/log4js/lib/appenders/fileSync.js:118:10)
    at RollingFileSync.write (/usr/lib/node_modules/@brightside/core/node_modules/log4js/lib/appenders/fileSync.js:129:5)
    at /usr/lib/node_modules/@brightside/core/node_modules/log4js/lib/appenders/fileSync.js:183:13
    at categoryAppenders.forEach (/usr/lib/node_modules/@brightside/core/node_modules/log4js/lib/log4js.js:42:5)
    at Array.forEach (<anonymous>)
    at sendLogEventToAppender (/usr/lib/node_modules/@brightside/core/node_modules/log4js/lib/log4js.js:41:21)
    at listeners.forEach.l (/usr/lib/node_modules/@brightside/core/node_modules/log4js/lib/clustering.js:16:26)
(node:26373) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26373) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
+ @brightside/core@2.0.0-next.201901181325
added 555 packages from 827 contributors and updated 1 package in 16.472s
```

**Comment by dkelosky** [comment] 2019-01-24 20:41
@AHumanFromCA - is this unhandled promise a bug by itself?

**Comment by AHumanFromCA** [comment] 2019-01-24 22:01
I would say the only thing that we could do here is catch it and spew FATAL ERROR to the console. Is that enough to classify this as a bug...probably. But does fixing the bug resolve the problem, no it just will say the same thing in much more detail.

**Comment by dkelosky** [comment] 2019-01-25 11:59
So you're telling me there's a bug...

**Comment by MarkAckert** [comment] 2022-09-30 14:40
Could not reproduce with current versions of zowe cli (v1-lts and v2-lts), redhat 8.6, and node 16. I did not see the error when running the commands as root, or as less privileged user. Closing this issue.

**Closed by MarkAckert** 2022-09-30 14:40 UTC
Labels: bug, priority-low
