### ISSUE TITLE
zowe config auto-init doesnt include trailing commas

### ISSUE THREAD

**Issue by dkelosky** [zowe/zowe-cli#1144] opened 2021-09-15 20:05 UTC
![image](https://user-images.githubusercontent.com/14940561/133501744-2330a7e0-a9de-4e1e-acad-67916c1a4cc3.png)

however, if you uncomment the line, `//"zosmf": "ibmzosmf"` doesn't include a trailing comma and can yield invalid syntax in the `zowe.config.json` file

**Comment by zFernand0** [comment] 2021-09-15 20:07
similar to #1049

**Comment by t1m0thyj** [comment] 2022-11-03 15:25
Closing as duplicate of #1049

**Closed by t1m0thyj** 2022-11-03 15:25 UTC
