### ISSUE TITLE
Error in base profile

### ISSUE THREAD

**Issue by jellypuno** [zowe/zowe-cli#816] opened 2020-09-11 14:05 UTC
I manually deleted all my base profile yaml file and when I try to login using zowe auth login apiml this error appears:

![image](https://user-images.githubusercontent.com/45042840/92934944-6bb3f580-f448-11ea-9001-b129b7634b61.png)

Expectation: Login should allowed and default.yaml will be created.

**Comment by dkelosky** [comment] 2020-09-11 14:08
As a work around, if you delete the `meta` file as well - does login work?

**Comment by jellypuno** [comment] 2020-09-11 14:10
I will try. I just created a default.yaml with ru=false then set it as default profile

**Comment by jellypuno** [comment] 2020-09-11 14:14
@dkelosky It worked. I have a question about this message:

Do you want to store the host, port, and token on disk for use with future commands? If you answer Yes, the credentials will be saved to a base profile named 'default'. If you answer No, the token will be printed to the terminal and will not be stored on disk. [y/N]: 

If I choose NO, how are we going to get the token from the terminal?

**Comment by dkelosky** [comment] 2020-09-11 14:16
When you say "we" do you mean Zowe Explorer?  Otherwise, users will copy / paste the token for subsequent CLI commands or set them in env vars.

**Comment by jellypuno** [comment] 2020-09-11 14:19
Yes, I meant ZE. how are we going to handle that? After login, get it from
response then save it in a variable?

Thanks,
Jessielaine Punongbayan

Software Engineer  |  Mainframe Software Division
CA Technologies, A Broadcom Company

office: +420226205908
CA CZ s.r.o  | V Parku 2308/8 | Praha 4, Chodov, 148 00
Jessielaine.Punongbayan@broadcom.com

**Comment by jellypuno** [comment] 2020-09-11 14:22
Apologies, as per discussion with my colleague, my question about the message was clarified. Thanks @dkelosky

**Comment by t1m0thyj** [comment] 2020-11-03 15:59
@jellypuno Can this issue be closed?

**Comment by jellypuno** [comment] 2020-11-03 16:05
@t1m0thyj it is not fixed yet. Dan just gave a work around but it doesn't fix my issue.

**Comment by zFernand0** [comment] 2021-07-22 15:19
Hey @jellypuno,
Based on the description of the issue, `zowe profiles delete base` was not used to delete the profile.
Since this was done manually, shouldn't the workaround (i.e. manually delete the meta.yaml) be the solution to the issue?

**Comment by jellypuno** [comment] 2021-07-22 16:04
@zFernand0 its just weird for me that the solution is to delete the meta yaml file in order for me to login again. I mean, I used the `default` name. It's a different question if set the default base profile to a different name. I am really expecting that I am able to login to the `default` base profile whether it is deleted via command or manually.

But I am okay to close this issue. Maybe its just me who wants this 😄

**Comment by zFernand0** [comment] 2021-07-22 16:43
I believe it's not advisable to delete profiles manually.
I'm afraid I could not find a note/warning about modifying or deleting content from the `~/.zowe` folder in the docs.
https://docs.zowe.org/stable/user-guide/cli-usingcli#using-profiles
Maybe an action item is to update the documentation with such information.
@jellypuno, thoughts?

**Comment by gejohnston** [comment] 2022-10-17 14:37
The documented command to delete a profile was not used, so the app did behave as designed. The "profiles" commands are deprecated in Zowe V2 and so those commands will no longer be enhanced. Therefore, I am closing this issue.

**Closed by gejohnston** 2022-10-17 14:37 UTC
Labels: enhancement, UX, priority-low
