### ISSUE TITLE
Daemon socket error on MacOs

### ISSUE THREAD

**Issue by gejohnston** [zowe/zowe-cli#1238] opened 2021-12-16 14:07 UTC
From Joe Winchester:

I extracted the macOS version and ran it however I get an error about a socket error.

7.0.0-next.202112102143
The daemon failed to run your command due to this error:
Socket is not connected (os error 57)
joewinchester@Joes-MBP-New CLI_Daemon %

**Comment by awharn** [comment] 2021-12-16 14:23
This appears to be a duplicate of #1192

**Comment by t1m0thyj** [comment] 2021-12-17 15:14
Confirmed with Joe that this is identical to #1192

**Closed by t1m0thyj** 2021-12-17 15:14 UTC
Labels: bug, daemon-mode
