### ISSUE TITLE
Broken link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-cli#1608] opened 2023-01-20 19:35 UTC
**Describe the bug**

A link in the Documentation Guidelines section of zowe-cli/CONTRIBUTING.md is broken. The link in question: [TPSRs section of documentation](https://zowe.github.io/docs-site/latest/appendix/tpsr.html)

**Comment by t1m0thyj** [comment] 2023-02-10 19:53
It seems that "Third Party Software Requirements" is no longer hosted on the docs site, but is now an external link to the docs-site repo (for example for Zowe 2.6: https://github.com/zowe/docs-site/tree/master/tpsr/tpsr-v2.6.x.md).

Perhaps we should now link to the Bill of Materials instead? https://docs.zowe.org/stable/appendix/bill-of-materials/

**Comment by adam-wolfe** [comment] 2023-02-13 19:00
> It seems that "Third Party Software Requirements" is no longer hosted on the docs site, but is now an external link to the docs-site repo (for example for Zowe 2.6: https://github.com/zowe/docs-site/tree/master/tpsr/tpsr-v2.6.x.md).
> 
> Perhaps we should now link to the Bill of Materials instead? https://docs.zowe.org/stable/appendix/bill-of-materials/

Not sure, it might make sense just to link to [https://github.com/zowe/docs-site/tree/master/tpsr/tpsr-v2.6.x.md](https://github.com/zowe/docs-site/tree/master/tpsr/tpsr-v2.6.x.md).

**Comment by t1m0thyj** [comment] 2023-02-13 19:59
> Not sure, it might make sense just to link to https://github.com/zowe/docs-site/tree/master/tpsr/tpsr-v2.6.x.md.

I agree that would be the most relevant URL to use, but the problem is it changes with each Zowe release since we don't have a `tpsr-latest.md` 🤔

**Comment by anaxceron** [comment] 2023-04-19 19:52
Ana -- fix this page
https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md

**Comment by zFernand0** [comment] 2023-04-28 12:12
Fixed in:
- #1704

**Closed by zFernand0** 2023-04-28 12:12 UTC
Labels: bug, documentation, priority-low, severity-low
