### ISSUE TITLE
Problem installing a plugin in Zowe @next

### ISSUE THREAD

**Issue by plavjanik** [zowe/zowe-cli#1340] opened 2022-03-17 15:38 UTC
Zowe CLI version:

```
$ zowe --version                                                                        
7.0.0-next.202203091358
```

Installing a plugin:
```
$ zowe plugins install @broadcom/sysview-for-zowe-cli
Plug-ins within the Imperative CLI Framework can legitimately gain
control of the zowe CLI application during the execution of every command.
Install 3rd party plug-ins at your own risk.

Registry = https://registry.npmjs.org/

_______________________________________________________________
Installed plugin name = '@broadcom/sysview-for-zowe-cli'

_____ Validation results for plugin '@broadcom/sysview-for-zowe-cli' _____

*** Warning: The version value (^6.30.0) of the plugin's '@zowe/cli' property is incompatible with the version value (7.0.0-next.202203101634) of the zowe command's 'version' property.

*** Warning: The version value (^4.13.0) of the plugin's '@zowe/imperative' property is incompatible with the version value (5.0.0-next.202203091934) of the zowe command's '@zowe/imperative' property.

This plugin has warnings, but its commands and framework overrides will still be available.
```

I expected what is written at the end: `commands and framework overrides will still be available.`

But commands for the plug-in are not there:
```
 GROUPS
 ------

   auth                          Connect to Zowe API ML authentication service
   config                        Manage JSON project and global configuration
   daemon                        Daemon operations
   plugins                       Install and manage plug-ins.
   profiles                      Create and manage configuration profiles.
                                 (deprecated)
   provisioning | pv             Perform z/OSMF provisioning tasks
   zos-console | console         Issue z/OS console commands and collect
                                 responses
   zos-files | files             Manage z/OS data sets
   zos-jobs | jobs               Manage z/OS jobs
   zos-logs | logs               Interact with z/OS logs
   zos-ssh | ssh | zos-uss | uss Issue z/OS USS commands and receive responses
   zos-tso | tso                 Interact with TSO
   zos-workflows | wf            Create and manage z/OSMF workflows
   zosmf
```

I would expected the installation of the plugin to fail with error and explanation if there is compatibility problem or see new commands if the message is correct. If I need to install a different version of the plug-in, I would like to see some advice on how to do it.

**Comment by radecek9787** [comment] 2022-04-13 16:14
This happens to me as well if I use a daemon mode. When I am in a daemon mode and install the plugin, I cannot see the plugin commands listed. When I restart the command prompt, the plugin commands are there.

**Comment by radecek9787** [comment] 2022-05-25 09:40
@zdmullen Yes, I think a message informing a user to restart daemon after installing a plugin would resolve this.

**Comment by MarkAckert** [comment] 2022-11-15 20:18
Could not reproduce the error on the most recent version of 7.x CLI. Closing.

```
zowe --version
7.8.0
```

```
zowe plugins install @broadcom/sysview-for-zowe-cli@zowe-v1-lts
Plug-ins within the Imperative CLI Framework can legitimately gain
control of the zowe CLI application during the execution of every command.
Install 3rd party plug-ins at your own risk.

Registry = https://registry.npmjs.org/

_______________________________________________________________
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
Installed plugin name = '@broadcom/sysview-for-zowe-cli'

_____ Validation results for plugin '@broadcom/sysview-for-zowe-cli' _____

*** Warning: The version value (^6.30.0) of the plugin's '@zowe/cli' property is incompatible with the version value (7.8.0) of the zowe command's 'version' property.

*** Warning: The version value (^4.13.0) of the plugin's '@zowe/imperative' property is incompatible with the version value (5.7.0) of the zowe command's '@zowe/imperative' property.

This plugin has warnings, but its commands and framework overrides will still be available.
```


(Abbreviated below for clarity)
```
zowe

 USAGE
 -----

   zowe <group>

   Where <group> is one of the following:

 GROUPS
 ------        
   sysview | sv                  Integration with SYSVIEW             
```

**Closed by MarkAckert** 2022-11-15 20:18 UTC
Labels: enhancement, documentation

**Comment by plavjanik** [comment] 2022-11-21 10:25
Thanks for verifying it!
