### ISSUE TITLE
Unable to securely save credentials

### ISSUE THREAD

**Issue by markklerks** [zowe/zowe-cli#1470] opened 2022-07-13 09:36 UTC
After upgrade on Windows of Zowe CLI it is not able to add secure credentials.
The same goes for separate commands ZOWE CONFIG INIT and ZOWE CONFIG SECURE.

Tried also clean installs for versions: 7.4.0  7.2.5  7.2.3
Tried with regular permissions and elevated administer permissions.

see attached Log from CMD for most of the attempts
[log from CMD.txt](https://github.com/zowe/zowe-cli/files/9100892/log.from.CMD.txt)

At this time I'm not able to create a working Zowe CLI environment on my system.
Anyone has a solution or work-around?

I also added some errors and warnings from my imp.log:
[errors and warmings.txt](https://github.com/zowe/zowe-cli/files/9101013/errors.and.warmings.txt)

**Comment by t1m0thyj** [comment] 2022-07-19 19:04
Verified that the issue has been fixed via email. It is caused by a bug in npm 8.11.0 and 8.12.0 that affects offline install of Zowe CLI. A workaround has been documented in https://github.com/zowe/docs-site/pull/2286

**Closed by t1m0thyj** 2022-07-19 19:04 UTC
