### ISSUE TITLE
Encoding in file-to-uss and dir-to-uss commands

### ISSUE THREAD

**Issue by Yuliya-Kirkorava** [zowe/zowe-cli#1479] opened 2022-08-03 12:15 UTC
Hi,
I have a question about "zowe zos-files upload dir-to-uss" and "zowe zos-files upload file-to-uss" commands.

For **file-to-uss** command we can specify an encoding for the file, and as I have already tested the uploaded symbols in this file are fine. But such file isn't tagged.

For **dir-to-uss** command we can create .zosattributes file where the local and remote encoding can be specify. But in reallity such file are not converted to remote encoding and just tagged with remote encoding.
My .zosattributes file is:
![image](https://user-images.githubusercontent.com/96059205/182604872-a47f2eb6-4bc7-4d44-8e59-12d2fe561318.png)

The result of the ssh command is:
![image](https://user-images.githubusercontent.com/96059205/182602198-afd3af48-1ba9-4f9e-a195-473c77911746.png)
But both files doesn't contain correct symbols in the files. I am a little bit confused.

My question: why do you have so different behaviour for similar commands? As I've already investigated your code **dir-to-uss** command also processes separate files for uploading (Upload.fileToUssFile) as the **file-to-uss** command does, but with different encoding file attributes.

Thanks!

**Comment by Yuliya-Kirkorava** [comment] 2022-08-10 07:46
Do you have any comments here?

**Comment by gejohnston** [comment] 2022-08-10 20:48
We have not yet tried to reproduce the behavior that you describe. However, the behavior that you describe does imply some inconsistency between the 'file-to-uss' and 'dir-to-uss' commands. It appears that one command converts the file encoding and the other command sets the tag. 

We do not foresee an opportunity to address this behavior in the next quarter due to other commitments. Up-votes on this issue will have an influence on the priority of this issue. 

You are welcome to join one of our team meetings to more fully describe your needs to the team. One decision will be whether the desired behavior should be for both commands to set the tag and also convert the file encoding.

If you are interested in discussing the issue with our team, the Zowe CLI team meetings occur in Zoom every Monday and Wednesday from 11:00 - 11:30 AM U.S. Eastern time.

Join Zoom Meeting
https://zoom.us/j/99891777715

**Comment by gejohnston** [comment] 2022-08-12 14:48
While working on a similar feature, this behavior has come better into focus. Rather than expand the inconsistency, we plan to make the encoding and tagging consistent throughout the upload and download commands.

We now plan to correct this behavior within this quarter. We will update this issue when there is a resolution.

**Comment by Yuliya-Kirkorava** [comment] 2022-08-12 19:34
Thank you very much for update! The correct encoding is very import for European users who support different encodings for ISPF panels (and not only in panels). My customer will be very glad that this bug will be fixed very soon!

**Comment by FALLAI-Denis** [comment] 2022-08-20 09:44
Hi,

I suggest also to consider issue #1463 I create.

Thanks.

**Comment by Yuliya-Kirkorava** [comment] 2022-10-19 09:04
Hi ,
Have you already fixed the encoding problem? 
Where can I find information about changes?

Thanks.

**Comment by t1m0thyj** [comment] 2022-10-20 19:20
@Yuliya-Kirkorava I believe the inconsistent encoding behavior between commands has been fixed in v7.6.0. The release notes can be found [here](https://github.com/zowe/zowe-cli/blob/master/packages/cli/CHANGELOG.md#760):
> - Enhancement: Updated the `zowe files upload file-to-uss` and `zowe files upload dir-to-uss` commands to improve how they handle file encoding. [#1479](https://github.com/zowe/zowe-cli/issues/1479)
>   - Both commands now "chtag" files after uploading them to indicate their remote encoding. This matches the already existing behavior of the `zowe files download uss-file` command which checks file tags before downloading.
>   - The behavior of ".zosattributes" files which can specify local and remote encoding has been changed. Files are now converted to the remote encoding, not just tagged. If no encoding is specified, the default transfer mode is text instead of binary to be consistent with z/OSMF default behavior.

These changes should address your comments:
> For **file-to-uss** command we can specify an encoding for the file, and as I have already tested the uploaded symbols in this file are fine. But such file isn't tagged.

The **file-to-uss** command now tags files after uploading them.

> For **dir-to-uss** command we can create .zosattributes file where the local and remote encoding can be specify. But in reallity such file are not converted to remote encoding and just tagged with remote encoding.

The **dir-to-uss** command now converts files that it uploads from local to remote encoding, instead of just tagging them.

The latest version of Zowe CLI can be obtained from npm (`npm install -g @zowe/cli@zowe-v2-lts`) or the CLI bundle on zowe.org.

**Comment by Yuliya-Kirkorava** [comment] 2022-10-21 15:11
Hi Timothy,

Thank you for the update! I've tested your changes and they look fine for me!
Symbals and tags after uploading are correct now!

One minor remark from my side... When I run dir-to-uss command I don't see a status bar for this command. I don't remember if I had seen it before your enhancement. Could you add it? 
If an upload folder contains a lot of files, an user couldn't understand what is going on for quite a long time.

Thanks.

**Comment by Yuliya-Kirkorava** [comment] 2022-10-24 18:39
@t1m0thyj ,
You can close this ticket. Thank you for the fix!

**Closed** 2022-10-24 19:36 UTC
Labels: bug
