### ISSUE TITLE
Include the `zowex` binary in our `next` bundle on our Zowe Downloads site

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-cli#1120] opened 2021-08-24 14:35 UTC
See title :yum:

[Zowe Downloads](https://www.zowe.org/download.html) site

_Originally posted by @MikeBauerCA in https://github.com/zowe/docs-site/pull/1785#r690701021_

**Comment by gejohnston** [comment] 2021-08-24 15:02
Should we delay taking this action until we decide to distribute the "auto-start" version of the zowe executable? I am not sure.

**Comment by MikeBauerCA** [comment] 2021-08-24 18:13
I think we should go ahead and include it. The "auto-start" version can be another incremental improvement.

**Comment by t1m0thyj** [comment] 2021-08-25 13:10
Is this a duplicate of https://github.com/zowe/zowe-cli-standalone-package/issues/37? 😋

**Closed as completed** 2021-08-26 11:53 UTC
Labels: daemon-mode
