### ISSUE TITLE
Upload DTU system test failing

### ISSUE THREAD

**Issue by ChrisBoehmCA** [zowe/zowe-cli#350] opened 2019-04-26 18:22 UTC
As reported by @matthewpwilson, this test is failing right now in master and I believe lts-incremental 
```
Upload directory to USS › Success scenarios › should give error when upload local directory to
 USS directory in default ascii if it contains also binary files

    expect(received).toContain(expected) // indexOf

    Expected substring: "Rest API failure with HTTP(S) status 500"
    Received string:    ""Upload directory to USS › Success scenarios › should give error when upload local directory to
 USS directory in default ascii if it contains also binary files

    expect(received).toContain(expected) // indexOf

    Expected substring: "Rest API failure with HTTP(S) status 500"
    Received string:    ""
```

It's expecting the upload to fail but it gets success instead.

**Comment by tjohnsonBCM** [comment] 2020-01-09 20:00
This seems to be a platform-specific bug. The test fails in Linux (CentOS 7.6) because the expected error does not happen.

On Windows 10 however, the test passes, and attempting to reproduce the issue in the CLI resulted in the following error message:
```
z/OSMF REST API Error:
Rest API failure with HTTP(S) status 500
category: 16
rc:       147
reason:   -1033961426
message:  Illegal character sequence detected by iconv()
details: 
  - EDC5147I Illegal byte sequence. (errno2=0xC25F002E)
```

**Comment by gejohnston** [comment] 2022-10-11 15:02
This issue appears to be outdated. No test with this specific wording currently exists. The current tests pass, so I am closing this issue.

**Closed by gejohnston** 2022-10-11 15:02 UTC
Labels: testing, priority-low
