### ISSUE TITLE
[next] zowe.config.json in a home directory is not considered in selection if zowe.config.user.json exists in the project folder

### ISSUE THREAD

**Issue by radecek9787** [zowe/zowe-cli#1358] opened 2022-03-29 16:00 UTC
Run `zowe config init --global-config`. It will create a `zowe.config.json` in your home directory. Then open it and set it up.

Run any zowe command that is using properties of that global config file.

Run `zowe config init --user-config`. It will create a` zowe.config.user.json` in your project directory. Then open it and set just one variable to override the global config. Make sure that the profile you use contains any required options that are defined in the global config file in your home directory.

Run any zowe command that is using properties of that global config file. The error message tells you that the other options are required but missing. However, you have these options defined in the global config file.

Copy the `zowe.config.json` from your home directory to the project directory. 

Repeat the zowe command. It starts to work.

**Comment by gejohnston** [comment] 2022-12-16 20:29
The user $HOME directory plays no special role in the configuration overrides. The --global-config flag places the config file in the $ZOWE_CLI_HOME directory.

We feel that this use just a mistake in usage. We are closing this issues as working as designed.

**Comment by radecek9787** [comment] 2022-12-19 10:44
Hi Gene,

Thanks for looking into this. The point is not about the HOME directory where the config file is created, but about combining values of the global and user configs.

When I reported this, I had a global config file and a user config file created. I updated one value in the user config file and expected the other values will be taken from the global config. But I got errors. It only started to work after copying the global config file to the same folder where my user config file was sitting.

Thanks,
Radek

**Comment by zFernand0** [comment] 2022-12-19 16:28
We believe this might be related to:
- #1245 

Let's track the doc update there 😋

**Comment by radecek9787** [comment] 2022-12-20 11:17
I think #1245 is about the location where the config files are created. But I think I understand it now, based on the following comment (if the doc will be updated by this, it will become clear):

- By global config, we mean that configuration will be applicable wherever you run commands (the directory you are in doesn't matter). This is similar to how Zowe V1 works today.

- Global config lives in a zowe.config.json file in the zowe home directory.

- Global config can be overridden by a global user config zowe.config.user.json in that same directory.

- Project config is only applicable when you are in a directory that contains a zowe.config.json (or you are beneath that directory). Project config is a new concept in Zowe V2. One use case is that it allows you to easily switch contexts/projects without needing to adjust all your default profiles.

- Project config can live in any directory that is not the zowe home directory.

- Project config can be overridden by a project user config zowe.config.user.json in that same directory.


The issue I reported here probably occurred because the global user config file was created in my project directory, not the zowe home directory. Based on the above description, it should be located in the same directory as where the global config file zowe.config.json lives. That explains why it started to work when I added zowe.json.config to the project directory.

So I agree this can be closed as it more requires the documentation update, discussed in #1245.

Thank you and regards,
Radek

**Comment by gejohnston** [comment] 2023-01-06 16:20
I revisited this issue now that I better understand the scenario that demonstrates the behavior.

The properties of a profile are merged differently when a team config and user config are in the same directory versus when one is in the ZOWE_CLI_HOME directory and the other is in a project directory.

When a team configuration and a user configuration are placed at the same level (both files are in the ZOWE_CLI_HOME directory or both are in the same project directory), the merging of profile properties are done property-by-property. A profile property value in the user config will override a value in the team config file. If a profile property value exists in one config file but not the other, then that value will be also included in the merged set of properties used by a CLI command.

When configuration files (either team or user) exist at both the global level and in a project directory, a profile from a project config completely replaces a profile of the same name from the global config. All profiles that exist in one config file but **NOT** in the other config file are included in the resulting configuration that is used by a CLI command.

Here is what I think occurred in your scenario of initializing a team config at the global level and only initializing a user config at the project level:

The `zowe config init --user-config` command creates a set of empty profiles in the user config. The empty profiles in the user config will **COMPLETELY** replace profiles of the same name from a global config. Since your resulting profile is empty, you encounter the problems about required properties being missing.

You identified a way to make things work by copying your zowe.json.config to your project directory - and that is fine. However, if you want to use your original approach (global team config & project user config), you could also use the following techniques: 

You could override the zosmf port by adding the port property to the zosmf profile in the project user config, **AND** delete the empty base config in the project user config so that it does **NOT** override the global base profile (which contains host and rejectUnauthorized) with an empty base profile.

We might undertake a change in behavior, if we receive a groundswell of consumer requests for such a change. At this time, our team is reluctant to change the current behavior since the product is already in the field and such a modification would constitute a breaking change.

One action that does seem reasonable is to document the nuances of configuration merging. Therefore, I am reopening this issue as a documentation enhancement.

**Comment by t1m0thyj** [comment] 2024-04-22 16:28
Thanks to @anaxceron for enhancing our docs to better explain how team config files work at the global and project level:
https://docs.zowe.org/stable/user-guide/cli-using-understand-profiles-configs

**Closed by t1m0thyj** 2024-04-22 16:28 UTC
Labels: bug, priority-medium
