### ISSUE TITLE
ZOWE V2 SDK / CLI behaviour and many canceled jobs

### ISSUE THREAD

**Issue by kraabrsg** [zowe/zowe-cli#1410] opened 2022-05-10 05:05 UTC
Hi, 

we have done a vscode extension in combination with z open editor and zowe explorer.
At startup this happens:
```
    public static async initZosmfSession() {
        var args = (await ZoweCli.getProfileArgs("zosmf")).knownArgs;
        this.session = ProfileInfo.createSession(args);
    }
	
	//datasetname is:    username + ".*" 
	public static async listDataset(datasetName: string, opts: string) {
        // Logger.initLogger(LoggingConfigurer.configureLogger('lib', {name: 'test'}));
        // Uncommment the below line if the Secure Credential Store is in use, nur einmalig bei extension start in extension.tx
        // await CredentialManagerFactory.initialize({service: "Zowe-Plugin"});
        console.log("clizosmflistdataset " + opts);
        let response: IZosFilesResponse;
        const dataset: string = datasetName;
        const options: IListOptions = {};
        response = await List.dataSet(this.session, dataset, options);

        return response;
    };

```

before this happens the jobslist is:
![grafik](https://user-images.githubusercontent.com/86772851/167545283-76944870-54c6-4af2-81ff-f3b7edd09eaa.png)

After the code is executed at extension startup jobs get cancelled:
![grafik](https://user-images.githubusercontent.com/86772851/167545337-88ec8e4a-3681-4c0a-9032-84a9b2a9f548.png)

Seems that Sessions get cancelled and new started often, so one would assume that happens only once at startup of the extension.
![grafik](https://user-images.githubusercontent.com/86772851/167546030-49d6a386-416e-497d-bcd0-e96e714f51d0.png)

Users of the extensions get complaints why they are producing a lot of cancel jobs.
Our zos sysadmin tried to avoid that (i am not sure what they did exactly).

How to avoid this behaviour ?

Thanks!

**Comment by zFernand0** [comment] 2023-07-13 18:48
Hey @kraabrsg,

We have learned  from the IBM z/OSMF team that the numerous cancelled jobs are due to how z/OSMF operates behind the covers. It will spawn multiple TSO sessions and keep them alive for at least 10 minutes. A workaround that application developers have decided is to limit the number of concurrent requests, so that z/OSMF is effectively reusing the same session as much as practicable (e.g. https://github.com/IBM/zopeneditor-about/issues/134#issuecomment-1593827611) . Please note that these many canceled jobs are expected behavior and should not cause any harm to the system (other than filling up the spool eventually).

You may find more details as to how this occurs in this comment:
- https://github.com/IBM/zopeneditor-about/issues/134#issuecomment-1515039725

I believe that we can keep this in mind for future complex SDK implementations where we allow end users to customize the number of parallel requests. Other than that, please let us know if it ok to close the issue.

**Comment by kraabrsg** [comment] 2023-07-19 06:31
@zFernand0 Thanks it's ok!

**Closed** 2023-07-19 13:10 UTC
Labels: enhancement, priority-low
