### ISSUE TITLE
Installing dependencies fails

### ISSUE THREAD

**Issue by abastyr** [zowe/zowe-cli#176] opened 2019-01-16 14:45 UTC
## Steps to reproduce:

1. Clone the zowe-cli repository (master branch)
2. Open the terminal and go to the repository's folder
3. npm config set @brightside:registry https://api.bintray.com/npm/ca/brightside
4. npm install --registry https://registry.npmjs.org

## Output

```log
npm WARN tarball tarball data for @brightside/imperative@2.0.0-next.201901081528
sha1-s25vNlZA5oZXQ5DGtUZ3WFOi/UY=) seems to be corrupted. Trying one more time.
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\basad01\sandbox\
sues\zowe\zowe-cli\node_modules\.staging\@brightside\imperative-4d23ec5e\lib\cmd
rc\doc\option'
npm WARN tar ENOENT: no such file or directory, lstat 'C:\Users\basad01\sandbox\
sues\zowe\zowe-cli\node_modules\.staging\@brightside\imperative-4d23ec5e\lib'
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\basad01\AppData\Roaming\npm-cache\_logs

\2019-01-16T14_42_4
672Z-debug.log
```

[2019-01-16T14_42_48_672Z-debug.log](https://github.com/zowe/zowe-cli/files/2764577/2019-01-16T14_42_48_672Z-debug.log)

**Comment by abastyr** [comment] 2019-01-16 15:20
It seems I have found the workaround.

Running the

```sh
npm update --registry https://registry.npmjs.org
```

and then running the npm install... again looks like it installed the dependencies properly now.

**Comment by ChrisBoehmCA** [comment] 2019-01-16 16:19
Sorry for the issue. We are investigating the cause. I think it might be related to package-lock.json

**Comment by AHumanFromCA** [comment] 2019-01-16 16:26
It could be because of the package-lock having the registry for @brightside be different than what it was created with.

One thing that could be the problem is the package integrety

```
"@brightside/imperative": {
      "version": "2.0.0-next.201901081528",
      "resolved": "https://gizaartifactory.jfrog.io/gizaartifactory/api/npm/npm-release/@brightside/imperative/-/@brightside/imperative-2.0.0-next.201901081528.tgz",
      "integrity": "sha1-s25vNlZA5oZXQ5DGtUZ3WFOi/UY="
```

I know that @zFernand0 has been saying that Bintray has some problems with the package metadata and we might be moving to public npm because of this.

**Comment by abastyr** [comment] 2019-01-16 16:30
> I would bet if you used gizaartifactory as the `@brightside` registry then you probably wouldn't see this issue.

That is possible. However, the readme file shows both possibilities so I chose the one with the least amount of extra registration processes :)

**Comment by AHumanFromCA** [comment] 2019-01-16 16:50
Also we might want to see if we can report this error to npm, looks like it had an uncaught exception

**Comment by AHumanFromCA** [comment] 2019-01-16 16:56
> That is possible. However, the readme file shows both possibilities so I chose the one with the least amount of extra registration processes :)

Here's hoping we can move to public npm at some point :smile:

**Comment by ChrisBoehmCA** [comment] 2019-01-16 20:23
Please try against master now and let us know if this is resolved

**Comment by AHumanFromCA** [comment] 2019-01-17 15:49
Hi @abastyr,

There currently appears to be problems with Bintray overall. I can see the version of imperative there but it is not found by npm for some reason due to package metadata.

Unfortunately, we don't have a solution other than use gizaartifactory for now. I'm not sure what the rules are for giving people access there though, maybe @MarkAckert could chime in.

One thing that we are attempting to do is move off of Bintray to public npm to start solving some of our packages.

**Comment by ChrisBoehmCA** [comment] 2019-01-17 17:04
If you are just trying to install the CLI and not make changes to it, you can still do so by doing `npm install -g @brightside/core@next` and you will get an slightly older version of the CLI. Sorry for the inconvenience.

**Comment by MarkAckert** [comment] 2019-01-17 17:26
As @AHumanFromCA said, I don't think we can add you to gizaartifactory - access there is restricted. We will be publishing to publicly accessible registries in the near future, but we are not there yet. Another avenue for downloading the CLI is to grab the offline package from zowe.org here: https://zowe.org/download/ . The current version there is Zowe 0.9.5, which will give you a 2-4 week out of date version of Brightside (compared to the live repository).

**Comment by ChrisBoehmCA** [comment] 2019-02-21 18:41
This should be resolved now that bintray is working again

**Closed** 2019-02-21 19:16 UTC
